# ===================
# solver configuration
# ====================

# number of gpus to use, this will be ignored if we're not using multi-gpu training
num_gpus: 1
num_epochs: 10
num_samples_per_epoch: 10000

# run validation every N steps
vld_iter: 100

# checkpoints every N steps
checkpoint_iter: 100

experiment_dir: "exp1"
checkpoint_dir: "exp1/checkpoints"

# path to pre-trained weights to initialize model with before training
pretrained_weights: null


# ============
# model config
# ============
batch_size: 32
num_classes: 17
learning_rate: 0.00001
data_dims: [32, 32, 3]
weight_decay: 0.0005
